version: "3"

services:
  orthanc:
    image: jodogne/orthanc:1.9.1
    ports:
      - 127.0.0.1:8028:8042

  dino:
    image: ch00k/dino
    environment:
      DINO_SCP_HOST: ${DINO_SCP_HOST:-0.0.0.0}
      DINO_SCP_PORT: ${DINO_SCP_PORT:-5252}
      DINO_SCP_AET: ${DINO_SCP_AET:-DINO}
    ports:
      - 127.0.0.1:5252:5252
