name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ORC_COMPLETION_OUTPUT_DIR: /tmp

jobs:
  unit_test:
    runs-on: ubuntu-latest
    name: unit_test

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: make unit_test_coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unit_test
          fail_ci_if_error: true

  integration_test:
    runs-on: ubuntu-latest
    name: integration_test
    strategy:
      matrix:
        orthanc: [1.6.1, 1.7.4, 1.8.0]
    services:
      orthanc:
        image: ch00k/orthanc-nginx:${{matrix.orthanc}}
        ports:
          - 8028:80
        volumes:
          - orthanc:/etc/orthanc
    env:
      ORC_ORTHANC_ADDRESS: http://localhost:8028
      ORC_ORTHANC_USERNAME: orthanc
      ORC_ORTHANC_PASSWORD: orthanc
      ORC_DATAFILES_PATH: /tmp/orc_test_data

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: make integration_test_coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: integration_test
          fail_ci_if_error: true

  check_completion:
    runs-on: ubuntu-latest
    name: check_completion

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run check
        run: make check_completion
