name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  ORC_COMPLETION_OUTPUT_DIR: /tmp

jobs:
  with-follow-exec:
    runs-on: ubuntu-latest
    name: with-follow-exec

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install tarpaulin
        run: cargo install --git https://github.com/xd009642/tarpaulin.git --branch develop cargo-tarpaulin

      - name: run tests
        run: cargo tarpaulin --follow-exec --test slow -- --show-output

  without-follow-exec:
    runs-on: ubuntu-latest
    name: without-follow-exec

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install tarpaulin
        run: cargo install --git https://github.com/xd009642/tarpaulin.git --branch develop cargo-tarpaulin

      - name: run tests
        run: cargo tarpaulin --test slow -- --show-output

