name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    name: unit_test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: |
          # Pinning to 0.16.0 until https://github.com/xd009642/tarpaulin/issues/618 is fixed
          cargo install --version 0.16.0 cargo-tarpaulin && \
          cargo tarpaulin --bins --verbose --ignore-tests --all-features --workspace --timeout 120 --out Xml

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unit_test
          fail_ci_if_error: true

  integration_test:
    runs-on: ubuntu-latest
    name: integration_test
    services:
      orthanc:
        image: jodogne/orthanc:1.7.1
        ports:
          - 8024:8042
    env:
      ORC_ORTHANC_ADDRESS: http://localhost:8024
      ORC_ORTHANC_USERNAME: orthanc
      ORC_ORTHANC_PASSWORD: orthanc
      ORC_DATAFILES_PATH: /tmp/orc_test_data

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: |
          # Pinning to 0.16.0 until https://github.com/xd009642/tarpaulin/issues/618 is fixed
          cargo install --version 0.16.0 cargo-tarpaulin && \
          ./scripts/populate_orthanc.sh && \
          cargo tarpaulin --test integration --verbose --ignore-tests --all-features --workspace --timeout 120 --out Xml -- --test-threads=1

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: integration_test
          fail_ci_if_error: true

  check_completion:
    runs-on: ubuntu-latest
    name: check_completion

    env:
      ORC_COMPLETION_OUTPUT_DIR: /tmp/completion

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run check
        run: |
          mkdir $ORC_COMPLETION_OUTPUT_DIR
          cargo build
          diff ./completion $ORC_COMPLETION_OUTPUT_DIR
