name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  ORC_COMPLETION_OUTPUT_DIR: /tmp

jobs:
  unit_test:
    runs-on: ubuntu-latest
    name: unit_test

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: make unit_test_coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unit_test
          fail_ci_if_error: true

  integration_test:
    runs-on: ubuntu-latest
    name: integration_test
    strategy:
      matrix:
        orthanc: [1.6.1, 1.7.4, 1.8.2, 1.9.7, 1.10.1, 1.11.0]
    services:
      orthanc:
        image: jodogne/orthanc:${{matrix.orthanc}}
        ports:
          - 8028:8042
      dino:
        image: ch00k/dino
        env:
          DINO_SCP_HOST: ${{env.DINO_SCP_HOST}}
          DINO_SCP_PORT: ${{env.DINO_SCP_PORT}}
          DINO_SCP_AET: ${{env.DINO_SCP_AET}}
        ports:
          - 5252:5252
    env:
      ORC_ORTHANC_ADDRESS: http://localhost:8028
      ORC_ORTHANC_USERNAME: orthanc
      ORC_ORTHANC_PASSWORD: orthanc
      ORC_DATAFILES_PATH: /tmp/orc_test_data
      DINO_SCP_HOST: 0.0.0.0
      DINO_SCP_PORT: 5252
      DINO_SCP_AET: DINO

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: make integration_test

  integration_test_coverage:
    runs-on: ubuntu-latest
    name: integration_test_coverage
    services:
      orthanc:
        image: jodogne/orthanc:1.9.1
        ports:
          - 8028:8042
      dino:
        image: ch00k/dino
        env:
          DINO_SCP_HOST: ${{env.DINO_SCP_HOST}}
          DINO_SCP_PORT: ${{env.DINO_SCP_PORT}}
          DINO_SCP_AET: ${{env.DINO_SCP_AET}}
        ports:
          - 5252:5252
    env:
      ORC_ORTHANC_ADDRESS: http://localhost:8028
      ORC_ORTHANC_USERNAME: orthanc
      ORC_ORTHANC_PASSWORD: orthanc
      ORC_DATAFILES_PATH: /tmp/orc_test_data
      DINO_SCP_HOST: 0.0.0.0
      DINO_SCP_PORT: 5252
      DINO_SCP_AET: DINO

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: make integration_test_coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: integration_test
          fail_ci_if_error: true

  check_completion:
    runs-on: ubuntu-latest
    name: check_completion

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run check
        run: make check_completion
